#!/bin/bash
rcfiles=$HOME/.homesick/repos/dotfiles/bash
system=`$rcfiles/system`

export LANG="en_US.UTF-8"
export LC_COLLATE="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export LC_MESSAGES="en_US.UTF-8"
export LC_MONETARY="en_US.UTF-8"
export LC_NUMERIC="en_US.UTF-8"
export LC_TIME="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

# let gpg decrypting work
# Fixes: gpg: signing failed: Inappropriate ioctl for device
export GPG_TTY=$(tty)

# Set flag if this session is interactive
if [ -n "$PS1" ]; then
    INTERACTIVE_SESSION=true
fi

# setup homeshick
source $HOME/.homesick/repos/homeshick/homeshick.sh


# source color aliases
source $rcfiles/colors

# source aliases
source $rcfiles/aliases

# source bash completion
source $rcfiles/completion

# source platform-specific bashrc
if [ "$system" == "Linux" ]; then
    source $rcfiles/rc.linux
elif [ "$system" == "OSX" ]; then
    source $rcfiles/rc.osx
fi

# set hostname var
if [ ! -n "$HOSTNAME" ]; then
    HOSTNAME=`hostname -s`
fi

# so less can show unicode characters
export LESSCHARSET=utf-8

# fix sorting of ls: dotfiles first
export LC_ALL="C"

# set default editor to Vim
export EDITOR=vim

# ignore some controlling instructions
# HISTIGNORE is a colon-delimited list of exclusions
# the '&' is a special pattern which suppresses duplicate entires
export HISTIGNORE=$'[ \t*:&:[fb]g:exit:cd *:git push *'

# don't put duplicate lines or lines starting with a space in history
export HISTCONTROL=ignoreboth:erasedups
export HISTSIZE=10000
export HISTFILESIZE=$HISTSIZE
#export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"

# append to the history file instead of overwrite
shopt -s histappend

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# case insensitive globbing (used in pathname expansion)
shopt -s nocaseglob

# autocorrect typos in path names when using cd
shopt -s cdspell

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# enable some bash 4 features when possible:
# * `autocd`, e.g. `**/qux` will enter `./foo/bar/baz/qux`
# * recursive globbing, e.g. `echo **/*.txt`
#for option in autocd globstar; do
#    shopt -s "$option" 2> /dev/null
#done


if $INTERACTIVE_SESSION; then
    # if [[ -f /usr/local/bin/virtualenvwrapper.sh ]]; then
    #     source /usr/local/bin/virtualenvwrapper.sh
    # elif [[ -f /usr/bin/virtualenvwrapper.sh ]]; then
    #     source /usr/bin/virtualenvwrapper.sh
    # fi

    # setup prompt
    GIT_PS1_SHOWDIRTYSTATE=true

    PS1=""
    # username@host
    PS1=$PS1"${txtgrn}\u${txtwht}@${txtcyn}\H${txtwht}:"

    # stopped process count
    PS1=$PS1${txtylw}'$( if [ $(jobs -s | wc -l) -gt 0 ]; then echo "[\j]"; fi )'

    # current directory
    PS1=$PS1"${bldblu}\w"

    # git branch
    if type __git_ps1 >/dev/null 2>&1; then
        PS1=$PS1${txtylw}'$(__git_ps1 " (%s)")'
    fi

    # finish it
    PS1=$PS1"${txtwht}\$ ${txtdef}"

    export PATH="$HOME/bin:$PATH"
    export SVN_EDITOR=vim
fi

export PGDATA="/usr/local/var/postgres"


source $HOME/.local/bin/z.sh

export GOPATH=$HOME/golang
# mkdir -p $GOPATH
export PATH=$PATH:/usr/local/opt/go/libexec/bin

unset rcfiles system

# source local environment settings
if [ -f ~/.bash_local ]; then
    source ~/.bash_local
fi
